# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a18278dad5b05eb18a4f4535593c3f1a3cb535940812e93fe8614704bf734487acf6d32c69c2f13d0f3ba756992b07d7a10062c1b5c314077f140070292276

test:
  secret_key_base: 7ae713920a1b644b29c54576f9f287e181e5db90d84b7c214c079af2367e548c655f98bc4faad26f2f9a30d16e493152c6cff90b6631435aa311889b93508776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
